language: python

python:
  - "3.5"
  - "3.6"

sudo: false

before_install:
  - pip install flake8
  - pip install coveralls
  - cd django-prosoul && pip install -r requirements.txt && cd ..
  - cd django-prosoul && python manage.py makemigrations && cd ..
  - cd django-prosoul && python manage.py migrate && cd ..

script:
  - flake8 .
  - cd django-prosoul && python manage.py test && cd ..
