language: python

python:
  - "3.4"

sudo: false

before_install:
  - pip install flake8
  - pip install coveralls
  - pip install django
  - pip install requests
  - pip install matplotlib
  - pip install kidash
  - cd django-prosoul && python manage.py makemigrations && cd ..
  - cd django-prosoul && python manage.py migrate && cd ..

# install:
#   - ./setup.py install

script:
  - flake8 .
  - cd django-prosoul && python manage.py test && cd ..
